name: CI-Build

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "40 7 * * 1"

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  VCPKG_BINARY_SOURCES: 'clear;x-gha,readwrite'

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # opencascade is not available on macOS
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev libgl1-mesa-dev libglu1-mesa-dev

    - name: Cache vcpkg
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/vcpkg
          ${{ github.workspace }}/vcpkg_installed
        key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json', '.github/workflows/build.yml') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-

    - name: Set up vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        # v2025.09.17
        vcpkgGitCommitId: '4334d8b4c8916018600212ab4dd4bbdc343065d1'

    - name: Build (Release)
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'release-preset'
        buildPreset: 'release-preset'

    - name: Build (Debug)
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'debug-preset'
        buildPreset: 'debug-preset'
